vich_uploader:
    db_driver: orm

    mappings:
        art_images:
            uri_prefix: '%art_images%'
            upload_destination: '%kernel.project_dir%/public%art_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false

